function checkInfo() {
    $("input#song").val("");
    $("input#album").val("");
    $("input#artist").val("");

    var meta = {};

    var desc = $("#description .ytd-video-secondary-info-renderer").text();
	var verified_artist = $("#owner-container .badge-style-type-verified-artist").length == 1;
	var topic = $("yt-formatted-string#owner-name").text().endsWith(" - Topic");
	var auto_gen = (desc.match(/Provided to YouTube by|Auto-generated by YouTube./g) || []).length == 2;

	if ((verified_artist || topic) && auto_gen) {
		isTopic = true;
		var info = desc.split("\n\n");
		info[1].split(" · ").forEach(function(x, i) { if (i < 2) meta[i == 0 ? "song" : "artist"] = x; });
		meta.album = info[2];
	} else {
        isTopic = false;
		$($(".more-button")[0]).click();
		setTimeout(function() {
			$("h4#title").toArray().forEach(function(x, i, a) {
			    var title = x.textContent.trim().toLowerCase();
			    var text = x.parentElement.children[1].textContent.trim();
			    if (/song|artist|album/g.test(title)) meta[title] = text;
			});
			$($(".less-button")[0]).click();
		}, 35);
	}

	setTimeout(function() {
		$("input#song").val(meta.song);
		$("input#album").val(meta.album);
		$("input#artist").val(meta.artist);
	}, 50);
}